### ISSUE TITLE
error with  uwsgi --ini uwsgi.ini

### ISSUE THREAD

**Issue by lammh** [Lambda-3/PyCobalt#4]
File "./pycobalt/resolving.py", line 45
    def resolve(text: str,
                    ^
SyntaxError: invalid syntax

**Comment by bermeitinger-b** [comment]
I guess you're not using a Python version that supports type hinting. This is at least supported with Python 3.5. The README states that it requires at least 3.6, so could you try with this?

**Comment by lammh** [comment]
ok think's for your response
